AWSTemplateFormatVersion: '2010-09-09'
Resources:
  PublicS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: s3-bucket-rfp-panw
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        RestrictPublicBuckets: false
      Tags:
        - Key: Project
          Value: RFP_PANW
